---
abstract: 'be like TOBYINK and use these stuffz'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Task::BeLike::TOBYINK
name: Task-BeLike-TOBYINK
no_index:
  directory:
    - inc
    - xt
requires:
  Task::BeLike::TOBYINK::Data: 0
  Task::BeLike::TOBYINK::Moose: 0
  Task::BeLike::TOBYINK::Packaging: 0
  Task::BeLike::TOBYINK::Plack: 0
  Task::BeLike::TOBYINK::RDF: 0
  Task::BeLike::TOBYINK::Utils: 0
  Task::BeLike::TOBYINK::Web: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Task-BeLike-TOBYINK
  homepage: https://metacpan.org/release/Task-BeLike-TOBYINK
  license: http://dev.perl.org/licenses/
version: 2012.155
